server:
  port: 8190
  servlet:
    context-path: /ogarnizer

api:
  ogarnizerAPI:
    url: http://localhost:8180/zajavka-ogarnizerAPI

spring:
  security:
    enabled: true
#    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ogarnizer
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE